---
name: "PR title check"
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - "**"

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        id: check_pr_title
        uses: actions/github-script@v7
        with:
          result-encoding: string
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = context.payload
            const prTitle = payload.pull_request.title

            // The pattern for JIRA ticket format
            const jiraPattern = /^\[[A-Z]{3}-\d+\]/;

            let message = '';
            if (!jiraPattern.test(prTitle) && !prTitle.startsWith('[NOJIRA]')) {
              console.log('The PR title does not match JIRA ticket format!');
              message = `**PR title does not match the JIRA ticket format!**

              Please add the ticket number to the PR title in the format:

              \`\`\`
              [XXX-123] Your title goes here
              \`\`\`

              or add \`[NOJIRA]\` at the beginning of the title if there's no linked ticket:

              \`\`\`
              [NOJIRA] Your title goes here
              \`\`\`
            `;
              core.setFailed('PR title does not match JIRA ticket format!');
            } else if (prTitle.startsWith('[NOJIRA]')) {
              message = 'PR starts with `[NOJIRA]`. Link creation skipped.';
            } else {
              const ticketId = prTitle.match(jiraPattern)[0].replace('[', '').replace(']', '');
              message = `Link to ticket: [${ticketId}](https://amenitiz.atlassian.net/browse/${ticketId})`;
            }

            core.setOutput('message', message);
            return message;

      - name: Check for existing comment
        id: check_comment
        if: ${{ !cancelled() }}
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: "JIRA ticket link:"

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ !cancelled() }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## JIRA ticket link:

            ${{ steps.check_pr_title.outputs.result }}

          comment-id: ${{ steps.check_comment.outputs.comment-id }}
          edit-mode: replace
