---
name: Lint yaml files

on:
  pull_request:
    branches:
      - main

jobs:
  lint-yaml-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint workflows
        run: |
          yamllint --help
          yamllint .github/workflows/*.yaml
          yamllint .github/workflows/*.yml
