---
name: Tag Release to Main

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          fetch-tags: 'true'

      - name: Generate and push tag to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG="$(git tag --list "v*" | sort --version-sort | tail --lines 1)"

          if [ -z "$LATEST_TAG" ]; then
            MAJOR_VERSION=0
            MINOR_VERSION=0
          else
            MAJOR_VERSION="$(echo "$LATEST_TAG" | cut -d '.' -f 1 | cut -d 'v' -f 2)"
            MINOR_VERSION="$(echo "$LATEST_TAG" | cut -d '.' -f 2)"
          fi

          NEW_TAG="v$MAJOR_VERSION.$((MINOR_VERSION + 1))"
          gh release create "$NEW_TAG" --title "$NEW_TAG" --generate-notes --target main
