---
name: Terraform Lint on PR

on:
  pull_request:
    branches:
      - main

jobs:
  terraform_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Lint
        run: |
          terraform fmt -check=true -recursive=true .
          terraform validate
